name: Build and Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build_linux_x86:
    name: Build linux x86
    strategy:
      matrix:
        go: [ 1.22 ]
    runs-on: [self-hosted, Linux, X64]
    needs: [build_public, build_common]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - env:
          OUTPUT1: ${{needs.build_public.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: public_build
          path: ./build

      - name: Go mod tidy
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: trying to build
        id: build-linux-x86
        run: make build_linux_x86

      - uses: actions/download-artifact@v4
        with:
          name: common_build
          path: ./server-linux-x86

      - name: trying to build docker image
        run: make docker_image_linux_x86

      - name: upload server linux x86
        uses: softprops/action-gh-release@v1
        with:
          files: ./server-linux-x86.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_amd64:
    name: Build linux amd64
    strategy:
      matrix:
        go: [ 1.22 ]
    runs-on: [self-hosted, Linux, X64]
    needs: [build_public, build_common]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - env:
          OUTPUT1: ${{needs.build_public.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: public_build
          path: ./build

      - name: Go mod tidy
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: trying to build
        id: build-linux-amd64
        run: make build_linux_amd64

      - uses: actions/download-artifact@v4
        with:
          name: common_build
          path: ./server-linux-amd64

      - name: trying to build docker image
        run: make docker_image_linux_amd64

      - name: upload server linux amd64
        uses: softprops/action-gh-release@v1
        with:
          files: ./server-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_arm6:
    name: Build linux arm6
    strategy:
      matrix:
        go: [ 1.22 ]
    runs-on: [self-hosted, Linux, X64]
    needs: [build_public, build_common]
    steps:

      - env:
          OUTPUT1: ${{needs.build_public.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: public_build
          path: ./build

      - name: Go mod tidy
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: trying to build
        id: build-linux-arm-6
        run: make build_linux_armv6

      - name: upload server linux armv6
        uses: softprops/action-gh-release@v1
        with:
          files: ./server-linux-arm-6.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_arm7:
    name: Build linux arm7
    strategy:
      matrix:
        go: [ 1.22 ]
    runs-on: [self-hosted, Linux, X64]
    needs: [build_public, build_common]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - env:
          OUTPUT1: ${{needs.build_public.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: public_build
          path: ./build

      - name: Go mod tidy
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: trying to build
        id: build-linux-armv7l
        run: make build_linux_armv7l

      - uses: actions/download-artifact@v4
        with:
          name: common_build
          path: ./server-linux-arm-7

      - name: trying to build docker image
        run: make docker_image_linux_armv7l

      - name: upload server linux armv7
        uses: softprops/action-gh-release@v1
        with:
          files: ./server-linux-arm-7.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux_arm64:
    name: Build linux arm64
    strategy:
      matrix:
        go: [ 1.22 ]
    runs-on: [self-hosted, Linux, X64]
    needs: [build_public, build_common]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - env:
          OUTPUT1: ${{needs.build_public.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: public_build
          path: ./build

      - name: Go mod tidy
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: trying to build
        id: build-linux-arm64
        run: make build_linux_arm64

      - uses: actions/download-artifact@v4
        with:
          name: common_build
          path: ./server-linux-arm64

      - name: trying to build docker image
        run: make docker_image_linux_arm64

      - name: upload server linux arm64
        uses: softprops/action-gh-release@v1
        with:
          files: ./server-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_image_upload:
    name: Upload docker images
    runs-on: [self-hosted, Linux, X64]
    needs: [build_linux_arm64, build_linux_amd64, build_linux_arm7, build_linux_x86]
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: trying to upload docker image
        run: make docker_image_upload
